name: Tests

# Trigger on push
on: push

jobs:
  build:

    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Install dependencies
      working-directory: ./SAKPaaS
      run: npm install
    - name: Lint
      working-directory: ./SAKPaaS
      run: npm run lint
    - name: Build
      working-directory: ./SAKPaaS
      run: npm run build -- --prod
    - name: Test
      working-directory: ./SAKPaaS
      run: npm test -- --configuration=ci
